baseURL = 'https://f3sch.github.io/'
languageCode = 'en-us'
title = 'f3sch blog'
theme = "m10c"
avatar = "/static/avatar.jpg"
copyright = "GPL-2.0"
[author]
  name = 'Felix Schlepper'

[menu]
  [[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 1
  [[menu.main]]
    identifier = "blog"
    name = "Blog"
    url = "/blog/"
    weight = 2
  [[menu.main]]
    identifier = "books"
    name = "Books"
    url = "/books/books"
    weight = 3
  [[menu.main]]
    identifier = "tags"
    name = "Tags"
    url = "/tags/"
    weight = 4
  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 5

[params]
    author = "Felix Schlepper"
    description = "Student"
    menu_item_separator = " â€¢ "
    #Social links
    [[params.social]]
        icon = "github"
        name = "Github"
        url = "https://github.com/f3sch"
    [[params.social]]
        icon = "rss"
        name = "RSS"
        url = "https://f3sch.github.io/blog/index.xml"


    #Default theme
    [params.style]
        darkestColor = "#282a36"
        darkColor = "#1E2029"
        lightColor = "#e2e2dc"
        lightestColor = "#f8f8f2"
        primaryColor = "#bd93f9"
